### ISSUE TITLE
Don't include the JSX Transformer in index.html

### ISSUE THREAD

**Issue by ryasmi** [samspot/react-requirejs-example#1]
You're missing the [required configuration](https://github.com/philix/jsx-requirejs-plugin#configuration-options-) for this to work in the main.js file.

**Additional links**
https://github.com/samspot/react-requirejs-example/blob/master/index.html#L9-L10
https://github.com/samspot/react-requirejs-example/blob/master/js/main.js#L13-L15

**Comment by samspot** [comment]
Hi, are you referring to the TODO comment?

TODO: Find out why we have to explicitly include the JSXTransformer.js here

**Comment by ryasmi** [comment]
Yeah

**Comment by samspot** [comment]
Thanks, I don't think this is quite what I need, as it seems to be a solution for loading *.jsx files.  We don't have any of those in this project.  The JSX features just don't work w/o having that explicit include.

**Comment by ryasmi** [comment]
Why can't the files containing jsx have their extension changed to jsx.

**Comment by samspot** [comment]
We can try it. I thought you were saying I just needed to adjust the
require config.

**Comment by ryasmi** [comment]
To be honest I thought that was it, didn't realise the files had js as the
extension, my bad.

**Comment by samspot** [comment]
JSX Config turned out to be a red herring.  All I needed to do was remove type="text/js" from the script tag.  I verified this in the original version.  Here is the commit for the fix:

https://github.com/samspot/react-requirejs-example/commit/b1da28d6f539e3457035e06e3957569c276d83b1

I went ahead and checked in 0.8.0 -> 0.12.0 on everything and some other cleanup, as  well as the .jsx renames.

**Comment by ryasmi** [comment]
Nice one! Thanks for the fix and the link to the commit along with the explanation :+1:
